spring.application.name=api_gateway

server.port=8888
# Userss Service
#spring.cloud.gateway.routes[0].id=userss
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0]=Path=/gateway/userss/**
#
##this one is for to add /gateway in the url otherwise /userss/**    /userss is a requestMapping("/userss") in the controller
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
#
#
#
##---------------------------------------------------------------------------------------
##try this so that we can use the same url for all services
##spring.cloud.gateway.routes[0].filters[0]=RewritePath=/gateway/get/product/(?<segment>.*), /product/${segment}
##---------------------------------------------------------------------------------------
#
#
#spring.cloud.gateway.routes[1].id=payment
#spring.cloud.gateway.routes[1].uri=http://localhost:8082
#spring.cloud.gateway.routes[1].predicates[0]=Path=/gateway/payment/**
#spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
#
#spring.cloud.gateway.routes[2].id=product
#spring.cloud.gateway.routes[2].uri=http://localhost:8083
#spring.cloud.gateway.routes[2].predicates[0]=Path=/gateway/product/**
#spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1


eureka.client.serviceUrl.defaultZone=http://localhost:8761/registry/eureka

#enable dynamic routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

