spring.application.name=payment
# server port (different from user service)
server.port=8082
#
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/MicroPay


#communicates with configserver ------> optional:configserver: is a keyword and then url
spring.config.import=optional:configserver:http://localhost:9999/configserver

#enable dynamic routing
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

