spring.application.name=config-server

#works on whole project unlike requestmapping which works on a class
server.servlet.context-path=/configserver
server.port=9999

spring.cloud.config.server.git.uri=https://github.com/moresrinivas45/cloudconfig.git
#this is baseUR
#http://localhost:9999/configserver


#this is used to see if config server is connecting and bringing the info
#http://localhost:9999/configserver/app/default