spring.application.name=service-registry

server.port=8761




server.servlet.context-path=/registry

#To remove self registration of self eureka server
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

